//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Apartment
{
	apartmentId?: number;
	surface: number;
	number: number;
	floor: number;
	individualQuota: number;
	userId?: number;
	userName: string;
	mansionId?: number;
	mansionName: string;
	membersCount: number;
}
