//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import * as User from './User';
import * as ProviderBill from './ProviderBill';

export interface Mansion
{
	id?: number;
	address: string;
	totalFunds?: number;
	users: User.User[];
	bills: ProviderBill.ProviderBill[];
}
