//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum MonthEnum { 
	January = 0, 
	February = 1, 
	March = 2, 
	April = 3, 
	May = 4, 
	June = 5, 
	July = 6, 
	August = 7, 
	September = 8, 
	Octomber = 9, 
	November = 10, 
	December = 11
}
