//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import * as ProviderType from './ProviderType';

export interface Provider
{
	providerId?: number;
	unitPrice: number;
	name: string;
	cui: string;
	bankAccount: string;
	type: ProviderType.ProviderType;
}
