//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ProviderBill
{
	billId?: number;
	providerName: string;
	providerId?: number;
	units: number;
	other: number;
	paid: boolean;
	totalPrice?: number;
	providerUnitPrice?: number;
	dueDate: string;
	date: string;
	mansionId?: number;
	mansionName: string;
}
