//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface WaterConsumption
{
	id?: number;
	hotWaterUnits: number;
	coldWaterUnits: number;
	creationDate: string;
	userId?: number;
	userName: string;
	mansionId?: number;
	mansionName: string;
}
